services:
  kafka:
    image: docker.io/bitnami/kafka:3.9
    container_name: kafka_EG
    ports:
      - "9092:9092"
    volumes:
      - /d/Projects/25mini/kafka:/bitnami
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    restart: always

  zookeeper:
    container_name: zookeeper_EG
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - '2181:2181'
    volumes:
      - /d/Projects/25mini/zookeeper:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  db:
    image: mysql:8.0
    container_name: mysql_EG
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 114514
    ports:
      - "3306:3306"
    volumes:
      - /d/Projects/25mini/mysql:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis_EG
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /d/Projects/25mini/redis:/data

