mysql:
  dsn: username:password@tcp(addr)/dbname?options
  maxIdleConns: 20 # max-idle-connections
  maxOpenConns: 10 # max-open-connections

redis:
  addr: addr

kafka:
  addr: addr

jwt:
  key: secret-key-for-jwt
  ttl: 259200 # time to live

imgbed:
  accessKey: your-access-key
  secretKey: your-secret-key
  bucket: bucket-name
  imgUrl:   # img-store-url